### PR TITLE
PDF Viewing Feature

### PR DESCRIPTION
**Pull request by VitorVieiraZ**
This feature can be used to open PDF files using the user’s system default application viewer, and can open formats such as links, PDFs, Docx, etc.
1. In a form that allows multiline entries, add text to the "Form Layout" widgets. This can be done in the "Default Value" section, or within the "HtmlWidget" field.
2. To embed a PDF file in the project, use the following HTML format:
-    For the "Default Value" section, enter:
    -    **`'<a href="project://dummy.pdf">Open File</a>' `** (include the HTML code inside single quotes).
-    For direct entry in the "HtmlWidget", use:
    -    **`<a href="project://dummy.pdf">Open File</a>`** (able to enter the HTML code without quotes).
3. After synchronizing the project, check the app to ensure that the fields display the link reference correctly.
4. 
| HTML Link | Invalid File |
|--------|--------|
| |  |

5. When clicking into the HTML button, the PDF file will be opened using the default application of the system.
6. Additional Note: 

- In the case of a file inside a folder in the project directory, use the following format:
`<a href="project://files/sample.pdf">Open PDF File inside folder "files"</a>`
_sample.pdf file inside 'files' folder_

### CODE REVIEW

**Review by tomasMizera — CHANGES_REQUESTED** [review]

**Comment by tomasMizera** [comment]
Please merge master branch here to make CI working. We can then proceed with testing

**Review by tomasMizera — APPROVED** [review]
Just one small comment, otherwise it looks good :)

**Comment by tomasMizera** [comment]
Let's merge to master and then test from there

**Comment by jozef-budac** [comment]
I just tried this feature on the APK from this ticket and I always get an error message, that the file does not exist. Can you please check it?

My project is tc05_forms_derived and there is a tab called `Files`

**Comment by VitorVieiraZ** [comment]
> I just tried this feature on the APK from this ticket and I always get an error message, that the file does not exist. Can you please check it?
> 
> My project is tc05_forms_derived and there is a tab called `Files`

Tests successfully conducted. In the case of a file inside a folder in the project directory, use the following format: 

 `<a href="project://files/sample.pdf">Open PDF File inside folder "files"</a>`

 _sample.pdf file inside 'files' folder_

**Comment by jozef-budac** [comment]
@VitorVieiraZ I checked the project and I don't see a problem in the configuration. Do you see it? I tried it again and I was able to open TXT and DOCX files, but the PDF file was still unavailable. 
The configuration for it is `'<a href="project://sample.pdf">Open PDF File</a>'` and the sample.pdf file it is located in the root directory of the project. Am I doing something wrong?


https://github.com/MerginMaps/mobile/assets/83582181/7252006a-940b-4d14-80d1-c91b846c8c8e

**Comment by jozef-budac** [comment]
Now it looks great! I didn't find any more problems.

**Comment by jozef-budac** [comment]
Unfortunately, the files in sub-directories stopped working


https://github.com/MerginMaps/mobile/assets/83582181/dc0b2893-349c-443d-89cc-1459e166f010

**Comment by tomasMizera** [comment]
@VitorVieiraZ please merge master branch here - it will upload the build to iOS then too :)

**Comment by tomasMizera** [comment]
@jozef-budac Can you please retest this PR? We are mainly interested in PDFs so if they work we can merge it and fix other file types later.

**Comment by jozef-budac** [comment]
Right now I can't install the package

image

**Comment by tomasMizera** [comment]
@jozef-budac you can now test it on iOS too :)

**Comment by tomasMizera** [comment]
> @jozef-budac you can now test it on iOS too :)

24.5.622711

**Comment by tomasMizera** [comment]
It says `Failure, intent tag may have at most one action`

**Comment by tomasMizera** [comment]
After removing these two lines https://github.com/MerginMaps/mobile/blob/d3293dbe25074d9b0f19d6f3796bdb13e5f4ef5a/cmake_templates/AndroidManifest.xml.in#L110-L111

the code works as expected for me in the `tc05_forms_derived`

**Review by tomasMizera — CHANGES_REQUESTED** [review]
@VitorVieiraZ Can you please remove these two lines https://github.com/MerginMaps/mobile/blob/d3293dbe25074d9b0f19d6f3796bdb13e5f4ef5a/cmake_templates/AndroidManifest.xml.in#L110-L111 I believe we are ready for merge then 🥳

**Comment by jozef-budac** [comment]
Here is a video from Android 14

https://github.com/MerginMaps/mobile/assets/83582181/e9d59326-429a-4827-9fe4-dd8d3a4a3ea5

**Comment by jozef-budac** [comment]
@tomasMizera Yes I have programs to open such files. In some of the previous APKs I was able to open the files. I wrote a note "Now it looks great! I didn't find any more problems." But then it doesn't work anymore.

**Pull request merged**
