### PR TITLE
Try Qt 6.6.3

### LINKED ISSUE #3296: App crashes when screen is rotated during QR code scanning
To reproduce:
 - open QR code scanner
 - rotate screen
   - 💥 

Reproduced on Android, iOS works fine.

I managed to get the same stacktrace (crash) when doing the following:

 - Open form that has an image field and a QR code field
 - Add image
 - Immediately after the image is captured open the QR code scanner
  -  💥 

A Quick Google search showed this Qt bug: https://bugreports.qt.io/browse/QTBUG-119445 <-- the same stacktrace

I tried to apply the fix mentioned in this comment https://bugreports.qt.io/browse/QTBUG-119445?focusedId=760746&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-760746 but that only led to other issues with the camera.

One possible solution could be to lock the screen orientation when opening the QR code scanner, see https://stackoverflow.com/questions/34310349/temporarily-programmatically-disable-screen-rotation-in-qt

I did not test the current 2.5.0, so not sure if it is a regression or not.

### PR DESCRIPTION
**Pull request by wonder-sk**
- let's see if Qt 6.6.3 will help with #3296
- small fix in `update_qt_version.bash` (with `\'` sed does not work for me on linux)

Fixes #3296

### CODE REVIEW

**Comment by PeterPetrik** [comment]
Don’t you need new SDK too ?

**Comment by wonder-sk** [comment]
> Don’t you need new SDK too ?

I don't know :smile:

**Comment by wonder-sk** [comment]
This fixes a crash for me as described in https://github.com/MerginMaps/mobile/issues/3296#issuecomment-2051899124

Best if @tomasMizera checks if it also fixes the other crashes that I was unable to replicate

**Comment by tomasMizera** [comment]
@wonder-sk I confirm this fixes the mentioned camera issue for me (in both cases I reported) 👍🏻

**Pull request merged**
