### PR TITLE
send uuid in HTTP request

### PR DESCRIPTION
**Pull request by PeterPetrik**
Add GUID to each HTTP request and also show it in the diagnosis log. GUID is generated on first run or the app.
We use `X-Device-Id` with uuid as custom header

### CODE REVIEW

**Comment by tomasMizera** [comment]
The implementation looks good, let's see where to add it

**Comment by mostlyAtNight** [comment]
Hi @PeterPetrik ,

Regarding how to send it, I would also be fine with it going in its own header, we should be able to accomodate that in the backend.  [This SE page](https://stackoverflow.com/questions/3561381/custom-http-headers-naming-conventions) may be useful for how to name a new one if we cannot find something appropriate to put it into.

Re the implementation itself, I have a question.  I assume the UUID is automatically generated when the app is installed - is it subsequently readable and editable by the user?  If so, I'm not sure this would be wise and I would instead opt for it to be stored in scoped storage or similar so it's protected from editing/cloning.

**Comment by PeterPetrik** [comment]
Looks like non standart headers might be blocked by firewall, what name you suggest?

**Review by wonder-sk — APPROVED** [review]

**Comment by PeterPetrik** [comment]
@varmar05 can you please secure server implementation? thanks

**Pull request merged**
