### PR TITLE
arm64 macOS, zstd support

### PR DESCRIPTION
**Pull request by PeterPetrik**
arm64 macOS, zstd support (@saberraz @roelofvandijkO )

### CODE REVIEW

**Comment by PeterPetrik** [comment]
mobile-sdk: https://github.com/MerginMaps/mobile-sdk/pull/112

**Comment by PeterPetrik** [comment]
@jozef-budac we need to add  geotiff files compressed with zstd to test suite (@saberraz can help you prepare one if you do not have any)

**Review by tomasMizera — APPROVED** [review]
LGTM!

**Comment by jozef-budac** [comment]
Does somebody have a project with zstd? If yes, please share it with me. Thanks

**Comment by tomasMizera** [comment]
> Does somebody have a project with zstd? If yes, please share it with me. Thanks

@jozef-budac see this message https://github.com/MerginMaps/mobile/pull/3445#issuecomment-2119815698

**Comment by jozef-budac** [comment]
I tried to open project tc06_zstd with zstd compression and it worked well.

**Pull request merged**
