### PR TITLE
Working test version of Android PDF viewer

### PR DESCRIPTION
**Pull request by VitorVieiraZ**
In this test version, pressing the sync button opens the test PDF file at "https://www.orimi.com/pdf-test.pdf" using the default Android PDF viewer.

### CODE REVIEW

**Comment by tomasMizera** [comment]
Great, please try to pass the url of the pdf file from c++ now

**Comment by VitorVieiraZ** [comment]
> Great, please try to pass the url of the pdf file from c++ now

Changes applied

**Comment by tomasMizera** [comment]
@VitorVieiraZ Can you create a development branch for this feature? We can merge it there

**Comment by VitorVieiraZ** [comment]
> @VitorVieiraZ Can you create a development branch for this feature? We can merge it there

Branch ```feature/pdf-viewing``` created.

**Pull request merged**
