### PR TITLE
Fix not null value relation

### LINKED ISSUE #3418: Not null constraint not met when multiple values selected in drop down selector widget
When using the 'Value relation' widget and the 'Allow multiple selections' option is selected and the 'Not null' constraint is used, the app will fail to record the values selected if multiple values are chosen. The "Field should not be empty" error will show if the user selects multiple values in the drop-down menu. In order to remove the error message, the user must open the menu again and deselect one of the options and then select it again:

https://github.com/MerginMaps/mobile/assets/26321345/a544af58-d760-4ebf-ade1-b0beab8eb5d3

I have created a project to demonstrate the error: [support/drop-menu-test](https://app.merginmaps.com/projects/support/drop-menu-test/)

To reproduce the problem: 

1. download the project on the mobile app
2. open the project
3. press the 'Add' button to record a new feature
4. press 'Record' to create the feature
5. click on the drop-down menu on the 'path' field
6. select multiple options and press 'Confirm selection'
7. the 'Field should not be empty' error will show
8. reopen the drop-down menu
9. deselect one of the options and then select it again
10. press 'Confirm selection'

### PR DESCRIPTION
**Pull request by uclaros**
This is an attempt to Fix #3418

The bug is as follows:
Not null constraint on multi-select value relations is not met when selecting values,
but works OK as long as a single value is deselected.

If there is no not null constraint, the log looks like this when clicking _confirm selection_ :
```
"Search (0) completed after 7ms, results: 1191"
"Search (0) completed after 3ms, results: 10"
"Search (0) completed after 4ms, results: 1191"
DEBUG  QList(273)   QVariant(QString, "{BS04.01}")
DEBUG  QList(260, 261)   QVariant(QString, "{BS04.01}")
"Search (1) completed after 0ms, results: 10"
"Search (1) completed after 3ms, results: 1191"
```

When the not null constraint is set, there appears a binding loop :
```
"Search (2) completed after 6ms, results: 10"
"Search (5) completed after 13ms, results: 1191"
"Search (0) completed after 0ms, results: 10"
"Search (0) completed after 3ms, results: 1191"
DEBUG  QList(273)   QVariant(QString, "{BS04.01}")
DEBUG  QList(260, 261)   QVariant(QString, "{BS04.01}")
DEBUG  QList()   QVariant(QString, "{BS04.01}")
DEBUG  QList(273)   QVariant(Invalid)
qrc:/com.merginmaps/imports/MMInput/form/MMFormPage.qml:267:7: QML Loader: Binding loop detected for property "fieldValue"
DEBUG  QList(260, 261)   QVariant(Invalid)
DEBUG  QList()   QVariant(Invalid)
qrc:/com.merginmaps/imports/MMInput/form/MMFormPage.qml:267:7: QML Loader: Binding loop detected for property "fieldValue"
"Search (6) was canceled after 0ms, results: 120"
"Search (1) completed after 0ms, results: 10"
"Search (7) completed after 3ms, results: 1191"
```

And if a second value is checked and then immediately unchecked, it works correctly and the log is:
```
"Search (0) completed after 14ms, results: 1191"
"Search (0) completed after 3ms, results: 10"
"Search (0) completed after 3ms, results: 1191"
DEBUG  QList(273)   QVariant(QString, "{BS04.01}")
DEBUG  QList(260, 261)   QVariant(QString, "{BS04.01}")
DEBUG  QList()   QVariant(QString, "{BS04.01}")
"Search (1) completed after 0ms, results: 10"
"Search (1) completed after 3ms, results: 1191"
```

When unchecking a value, the array containing the selected ids is _copied_ 
```js
root.selected = root.selected.filter( ( x ) => x !== val )
```
which apparently fixes the issue...
So creating a copy of the array when adding values too brings us the expected behavior!

This is _fixing the symptom instead of the cause_, so @tomasMizera I think I need your wisdom!

### CODE REVIEW

**Comment by tomasMizera** [comment]
If you merge master here, the iOS CI will pass

**Comment by uclaros** [comment]
> Does it fix the issue now @uclaros? :)

Yes, this fixes it!

**Comment by tomasMizera** [comment]
Test CI failures seem unrelated

**Review by tomasMizera — APPROVED** [review]
Looking good! This is how it behaved previously

**Pull request merged**
